name: FGO Login System

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 0 * * *"
    - cron: "0 2 * * *"
    - cron: "30 3 * * *"
    - cron: "0 5 * * *"
    - cron: "30 6 * * *"
    - cron: "0 8 * * *"
    - cron: "30 9 * * *"
    - cron: "0 11 * * *"
    - cron: "30 12 * * *"
    - cron: "0 14 * * *"
    - cron: "30 15 * * *"
    - cron: "0 17 * * *"
    - cron: "30 18 * * *"
    - cron: "0 20 * * *"
    - cron: "30 21 * * *"
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Install Requeriments
        run: pip install -r https://raw.githubusercontent.com/O-Isaac/FGO-Daily-Login/master/requirements.txt

      - name: Gettings files from Repo
        uses: actions/checkout@v2

      - name: Execute main script
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
